CREATE TABLE "GCG_5815_SO_Label"(
 "LABEL_ID" IDENTITY DEFAULT '0',
 "SALES_ORDER_NO" CHAR(7),
 "CUSTOMER_NO" CHAR(6),
 "CREATE_USER" CHAR(8),
 "CREATE_USER_NAME" CHAR(50),
 "BI_RUN_ID" INTEGER,
 "CUSTOMER_NAME" CHAR(50),
 UNIQUE ("LABEL_ID"));
